apiVersion: v1  
kind: Route    
metadata:   
  labels: 
    name: myservice   
  name: myservice-route-unsecured 
  annotations:  
    virtual-server.f5.com/balance: least-connections-node 
spec: 
  host: mysite.example.com 
  path: "/myApp" 
  port: 
    targetPort: 80 
  to:  
    kind: Service 
    name: myservice