apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
 name: cc1
 namespace: utkg-ubuntu
spec:
 clusterNetwork:
   pods:
     cidrBlocks:
     - 192.0.2.0/16
   serviceDomain: cluster.local
   services:
     cidrBlocks:
     - 198.51.100.0/12
 topology:
   class: tanzukubernetescluster
   controlPlane:
     metadata: {}
     replicas: 1
   variables:
   - name: storageClasses
     value:
     - wcpglobal-storage-profile
   - name: ntp
     value: time1.vmware.com
   - name: vmClass
     value: best-effort-small
   - name: storageClass
     value: wcpglobal-storage-profile
   version: v1.22.13---vmware.1-tkg.1-zshippable
   workers:
     machineDeployments:
     - class: node-pool
       metadata: {}
       name: np-2
       replicas: 1