apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: 2019-07-22T06:23:37Z
  generation: 16
  labels:
    app: k8s-bigip-ctlr
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
  resourceVersion: "8484699"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/k8s-bigip-ctlr-deployment
  uid: 3d70eca2-ac49-11e9-b17c-fa163e967e5d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/defaultProfileName: unconfined
        seccomp.security.alpha.kubernetes.io/pod: unconfined
      creationTimestamp: null
      labels:
        app: k8s-bigip-ctlr
      name: k8s-bigip-ctlr
    spec:
      containers:
      - args:
        - --
        - --bigip-username=admin
        - --bigip-password=admin
        - --bigip-url=10.145.68.107
        - --bigip-partition=kubernetes
        - --pool-member-type=cluster
        - --openshift-sdn-name=/Common/openshift_vxlan
        - --manage-routes=false
        - --route-vserver-addr=172.16.3.5
        - --log-level=debug
        - --namespace=default
        - --route-label=systest
        - --insecure=true
        - --agent=as3
        - --http-listen-address=0.0.0.0:8080
        - --custom-resource-mode=true
        - --ipam=true
        - --as3-validation=true
        - --log-as3-response=true
        command:
        - /app/bin/dlv
        - --listen=:40000
        - --headless=true
        - --api-version=2
        - --accept-multiclient
        - --check-go-version=false
        - exec
        - /app/bin/k8s-bigip-ctlr
        image: amit49g/k8s-bigip-ctlr:ppp
        imagePullPolicy: Always
        name: k8s-bigip-ctlr
        ports:
        - containerPort: 40000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: f5-docker-images
      - name: bigip-login
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bigip-controller
      serviceAccountName: bigip-controller
      terminationGracePeriodSeconds: 30