apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: k8s-bigip-ctlr
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-bigip-ctlr
      name: k8s-bigip-ctlr
      annotations:
        seccomp.security.alpha.kubernetes.io/defaultProfileName: unconfined
        seccomp.security.alpha.kubernetes.io/pod: unconfined
    spec:
      containers:
        - args:
            - --bigip-username=admin
            - --bigip-password=admin
            - --bigip-url=10.145.69.190
            - --bigip-partition=openshift
            - --pool-member-type=cluster
            - --openshift-sdn-name=/Common/openshift_vxlan
            - --manage-routes=true
            - --manage-ingress=false
            - --route-vserver-addr=172.16.3.5
            - --log-level=debug
            - --namespace=default
            - --route-label=systest
            - --insecure=true
            - --agent=as3
            - --as3-validation=true
            - --default-ingress-ip=172.16.3.5
            - --log-as3-response=true
            - --override-as3-declaration=default/example-vs
            - --as3-post-delay=10
            - --tls-version=1.2
            - --cipher-group=/Common/f5-ecc
            - --ciphers=DES
            - cluster
          command:
          - /app/bin/k8s-bigip-ctlr
          image: ssurenr/k8s-bigip-ctlr:as3-dbg
          imagePullPolicy: Always
          name: k8s-bigip-ctlr
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: f5-docker-images
        - name: bigip-login
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bigip-ctlr
      serviceAccountName: bigip-ctlr
      terminationGracePeriodSeconds: 30
